Repository martin-zyb/Remc, pull requests merged in 2023-10, with the labels that each got.

#9 Add EventCategoryMouseButton to MouseButtonEvent
  Remc/src/Remc/Events/MouseEvent.h
Labels: Impact:Bug

#10 Removed warnings from External Dependencies
  Remc/src/Remc/Core/Log.h
Labels: Impact:Warning

#11 Removed redundant GetProjection()
  Remc/src/Remc/Scene/Scene.cpp
Labels: Impact:Optimization

#12 Fixed two includes to fit the convention and one typo
  Remc/src/Platform/OpenGL/OpenGLFramebuffer.cpp
  Remc/src/Platform/OpenGL/OpenGLTexture.cpp
  Remc/src/Remc/Renderer/Framebuffer.cpp
Labels: Impact:Maintenance
